jobs:
  - job: Ruby_mswin
    variables:        # Build variables are set in azure_pipeline_prereqs_*.ps1
      BASERUBY:       # full path to ruby.exe
      BUILD_PATH:     # PATH string with prereqs added
      GIT:            # full path to git.exe, uses 'no space' link
      JOBS:           # NUMBER_OF_PROCESSORS
      OPENSSL_DIR:    #
      SRC:            # source/repo directory
      VC_VARS:        # full path to correct vcvarsall.bat file
    timeoutInMinutes: 60
    pool:
      vmImage: vs2015-win2012r2
    strategy:
      maxParallel: 5
      matrix:
        vc12-x64:
          vs: 120
          VCVARS_PLATFORM: amd64
          Platform: x64
        vc14-x64:
          vs: 140
          VCVARS_PLATFORM: amd64
          Platform: x64
    steps:
      - powershell: ./tool/azure_pipeline_prereqs_vc.ps1
        displayName: $(System.JobName) install prerequisites
        continueOnError: true

      - script: set
        displayName: $(System.JobName) set

      - script: dir "%ProgramFiles%"
        displayName: $(System.JobName) ProgramFiles
        
      - script: dir "%ProgramFiles(x86)%"
        displayName: $(System.JobName) ProgramFiles(x86)

      - script: dir D:\msys64\usr\bin
        displayName: $(System.JobName) dir D:\msys64\bin

      - powershell: |
          Write-Host $env:path.substring(0,100)
          Write-Host "BASERUBY      $env:BASERUBY"
          Write-Host "BUILD_PATH:  "$env:BUILD_PATH.substring(0,100)
          Write-Host "GIT:          $env:GIT"
          Write-Host "JOBS:         $env:JOBS"
          Write-Host "OPENSSL_DIR:  $env:OPENSSL_DIR"
          Write-Host "SRC:          $env:SRC"
          Write-Host "VC_VARS:      $env:VC_VARS"
        displayName: $(System.JobName) build variables