jobs:
  - job: Ruby_mswin
    variables:        # Build variables are set in azure_pipeline_prereqs_*.ps1
      BASERUBY:       # full path to ruby.exe
      BUILD_PATH:     # PATH string with prereqs added
      GIT:            # full path to git.exe, uses 'no space' link
      JOBS:           # NUMBER_OF_PROCESSORS
      OPENSSL_DIR:    #
      SRC:            # source/repo directory
      VC_VARS:        # full path to correct vcvarsall.bat file
    timeoutInMinutes: 60
    pool:
      vmImage: vs2015-win2012r2
    strategy:
      maxParallel: 5
      matrix:
        vc12-x64:
          vs: 120
          VCVARS_PLATFORM: amd64
          Platform: x64
        vc14-x64:
          vs: 140
          VCVARS_PLATFORM: amd64
          Platform: x64
    steps:
      - powershell: ./tool/azure_pipeline_prereqs_vc.ps1
        displayName: System.JobName $(System.JobName) System.JobDisplayName  $(System.JobDisplayName) Install prerequisites
        continueOnError: true
      - script: set
        displayName: Agent.JobName $(Agent.JobName) set
      - powershell: |
          dir D:\msys64\usr\bin
          Write-Host "-----------------------------------------------------------------"
          Write-Host $env:path.substring(0,100)
          Write-Host "BASERUBY      $env:BASERUBY"
          Write-Host "BASERUBY      $env:BASERUBY"
          Write-Host "BUILD_PATH:  "$env:BUILD_PATH.substring(0,100)
          Write-Host "GIT:          $env:GIT"
          Write-Host "JOBS:         $env:JOBS"
          Write-Host "OPENSSL_DIR:  $env:OPENSSL_DIR"
          Write-Host "SRC:          $env:SRC"
          Write-Host "VC_VARS:      $env:VC_VARS"
          Write-Host "JobName:      $env:JOBNAME"
          Write-Host "AGENT_JOBNAME $env:AGENT_JOBNAME"
