variables:
  OPENSSL_DIR=D:\openssl
  ruby_path=D:\ruby
jobs:
  - job: Ruby_mswin
    timeoutInMinutes: 360
    pool:
      vmImage: vs2015-win2012r2
    strategy:
      maxParallel: 5
      matrix:
        vc12:
          vs: 120
        vc14:
          vs: 140
    steps:
      - script: set
        displayName: set
      - powershell: ./tools/pipeline_prereqs.ps1
        displayName: Install prerequisites
      - script: |
          set vcvars=%%^VS%VS%COMNTOOLS^%%..\..\VC\vcvarsall.bat
          echo "%vcvars%" amd64
          call "%vcvars%" amd64
          cl
          echo PWD %CD%
        displayName: Select VC Version
