jobs:
  - job: Ruby_mswin
    timeoutInMinutes: 360
    pool:
      vmImage: vs2015-win2012r2
    strategy:
      maxParallel: 5
      matrix:
        vc12:
          VSVER: 120
        vc14:
          VSVER: 140
    steps:
      - script: set
        displayName: set
      - script: dir C:\
        displayName: dir C:\
      - script: dir "%ProgramFiles%"
        displayName: dir %ProgramFiles%
      - script: |
          dir "%ProgramFiles(x86)%"
        displayName: dir %ProgramFiles(x86)%
      - script: dir D:\
        displayName: dir D:\
      - powershell: Get-ChildItem -Path C:\ -Include 7zip -Directory -Recurse -ErrorAction SilentlyContinue | select -expand fullname
#      - powershell: ./tools/pipeline_prereqs.ps1
#        displayName: Install prerequisites
#      - powershell: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "COMNTOOLS"))
#      - script: \
#          call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" amd64
#          'cl'
#          echo PWD %CD%
    