jobs:
  - job: WhatsHere
    timeoutInMinutes: 360
    pool:
      vmImage: vs2015-win2012r2
    strategy:
      maxParallel: 5
    steps:
      - script: set
        displayName: set
      - script: dir C:\
        displayName: dir C:\
      - script: dir "%ProgramFiles%"
        displayName: dir %ProgramFiles%
      - script: |
          dir "%ProgramFiles(x86)%"
        displayName: dir %ProgramFiles(x86)%
      - script: dir D:\
        displayName: dir D:\
