variables:
  BASERUBY:       # full path to ruby.exe
  BUILD_PATH:     # PATH string with prereqs added
  GIT:            # full path to git.exe, uses 'no space' link
  OPENSSL_DIR:    # 
  SRC:            # source/repo directory
  VC_VARS:        # full path to correct vcvarsall.bat file
jobs:
  - job: Ruby_mingw
    timeoutInMinutes: 60
    pool:
      vmImage: vs2015-win2012r2
    strategy:
      maxParallel: 5
    steps:
      - script: set
        displayName: set
      - powershell: ./tool/azure_pipeline_prereqs_mingw.ps1
        displayName: Install prerequisites
